### ISSUE TITLE
QR code failure

### ISSUE THREAD

**Issue by HenryWang001** [askrella/whatsapp-chatgpt#100]
┌   Whatsapp ChatGPT & DALL-E 
│
◇   ────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                   │
│  A Whatsapp bot that uses OpenAI's ChatGPT and DALL-E to generate text and images from a prompt.  │
│                                                                                                   │
├───────────────────────────────────────────────────────────────────────────────────────────────────╯
│
○  Starting
/root/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/root/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/root/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by RG7279805** [comment]
@HenryWang001 you should install chrome or chromium (linux)

**Comment by siulynot** [comment]
I am getting a cut QR code that cant be scanned:
![image](https://user-images.githubusercontent.com/225342/222520874-4e5a0835-8a40-4115-9c4a-e66f343cb3e4.png)

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
