### ISSUE TITLE
Running whatsapp-chatgpt on RaspberryPi

### ISSUE THREAD

**Issue by byt3magic** [askrella/whatsapp-chatgpt#103]
```
○  Starting
/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: Syntax error: ")" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.14.1

```

Any ideas?

**Comment by connorv001** [comment]
Try apt install chromium

**Comment by byt3magic** [comment]
> Try apt install chromium

I already did that. I've read that apt install google-chrome 
might help. I'll try that as soon as I get back to my screen.

**Comment by RG7279805** [comment]
i had this same issue solved it by 
``` sudo apt-get install chromium-browser ```
if this didnt work try setting path for chromium in code

```javascript
const browser = await puppeteer.launch({
  executablePath: '/usr/bin/chromium-browser'
})
```
inside ["puppeteer"](https://github.com/askrella/whatsapp-chatgpt/blob/master/src/index.ts#L18) object

```javascript
puppeteer: {
   args: ["--no-sandbox"],
   executablePath: '/usr/bin/chromium-browser'
   }
```
I dont have a exact snippet to copy paste but this should do the trick.
if you still encounter any issue let me know i will try reproducing it on my own PI

**Comment by byt3magic** [comment]
This worked.

The lines are in src/index.ts

**Comment by RG7279805** [comment]
@byt3magic Do you mean adding executable path worked.
If yes then you can close the issue now I think

**Comment by byt3magic** [comment]
Yes.
