### ISSUE TITLE
RaspberryPi torch missing

### ISSUE THREAD

**Issue by byt3magic** [askrella/whatsapp-chatgpt#105]
```
◇  [Transcription] Transcribing audio with "local" mode...
Traceback (most recent call last):
  File "/home/pi/.local/bin/whisper", line 5, in <module>
    from whisper.transcribe import cli
  File "/home/pi/.local/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: whisper /tmp/9e1e7e2c-e5bb-45d6-b013-7e9a6c04745a.wav
Traceback (most recent call last):
  File "/home/pi/.local/bin/whisper", line 5, in <module>
    from whisper.transcribe import cli
  File "/home/pi/.local/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

    at checkExecSyncError (node:child_process:885:11)
    at Proxy.execSync (node:child_process:957:15)
    at Module.transcribeAudioLocal (/home/pi/whatsapp-chatgpt/src/providers/whisper-local.ts:14:17)
    at Module.handleIncomingMessage (/home/pi/whatsapp-chatgpt/src/handlers/message.ts:46:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.<anonymous> (/home/pi/whatsapp-chatgpt/src/index.ts:78:3) {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    'Traceback (most recent call last):\n' +
      '  File "/home/pi/.local/bin/whisper", line 5, in <module>\n' +
      '    from whisper.transcribe import cli\n' +
      '  File "/home/pi/.local/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>\n' +
      '    import torch\n' +
      "ModuleNotFoundError: No module named 'torch'\n"
  ],
  pid: 30014,
  stdout: '',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/home/pi/.local/bin/whisper", line 5, in <module>\n' +
    '    from whisper.transcribe import cli\n' +
    '  File "/home/pi/.local/lib/python3.9/site-packages/whisper/__init__.py", line 8, in <module>\n' +
    '    import torch\n' +
    "ModuleNotFoundError: No module named 'torch'\n"
}

Node.js v18.14.2
```

`ModuleNotFoundError: No module named 'torch'`

**Comment by byt3magic** [comment]
Yes. Doesn't work.

**Comment by RG7279805** [comment]
I am not sure about the exact problemm here but try this article it can maybe help you 
https://medium.com/secure-and-private-ai-writing-challenge/a-step-by-step-guide-to-installing-pytorch-in-raspberry-pi-a1491bb80531

if the problem still persists let me know i will try reproducing it on my PI

**Comment by MrPeterJin** [comment]
Hi, what's your model type of your Raspberrypi and what OS is running on your device?
