### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by AlessandroAnnini** [askrella/whatsapp-chatgpt#155]
I have just updated my Linode instance with the last version (34bfdfd6a09567556f4d246740a299ab33ccc2b8) but I have this error:

```bash
◇  [GPT] Received prompt from XXXXXXXXXX@c.us: hello
◇  [GPT] New conversation for XXXXXXXXXX@c.us (ID: da4f655e-113e-XXXX-XXXX-XXXXXXXXXXXXX)
An error occured Error: Request failed with status code 404
    at ChatGPT.askStream (file:///root/whatsapp-chatgpt/node_modules/chatgpt-official/src/classes/chatgpt.ts:154:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChatGPT.ask (file:///root/whatsapp-chatgpt/node_modules/chatgpt-official/src/classes/chatgpt.ts:97:10)
    at Module.handleMessageGPT (/root/whatsapp-chatgpt/src/handlers/gpt.ts:63:15)
    at Module.handleIncomingMessage (/root/whatsapp-chatgpt/src/handlers/message.ts:131:3)
    at Client.<anonymous> (/root/whatsapp-chatgpt/src/index.ts:85:3)
```

**Comment by navopw** [comment]
Is this error still occuring?

**Comment by miguelowsky-js** [comment]
I have the exact same error, anyone fixed it?

**Comment by AlessandroAnnini** [comment]
just updated and checked, the error is still there for me

**Comment by kingofkillers91** [comment]
Same for me, on Linode docker container.

**Comment by aaronyw** [comment]
same error

**Comment by AlessandroAnnini** [comment]
I can confirm that is working with the default but not with gpt-4 model

**Comment by kingofkillers91** [comment]
It works with 3.5 model.

**Comment by navopw** [comment]
@AlessandroAnnini Do you have gpt-4 access?

**Comment by AlessandroAnnini** [comment]
I confirm that you're right, I still don't have the access to gpt-4, the error message is not super informative but yeah, understandable
