### ISSUE TITLE
throw new Error('Evaluation failed: ' 

### ISSUE THREAD

**Issue by crypticatul** [askrella/whatsapp-chatgpt#177]
Hi folks

I have experienced some users deleting a message from the chat or content moderation fails, the code throws an exception and the server stops working, and needs to be restarted by "npm start"

The full error message is 👇🏻

OpenAI request took 9864ms)
/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isNewsletter')
    at Object.t.canReplyMsg (https://web.whatsapp.com/appxxxxxxxxxxxxxxx)
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:41)
    at __puppeteer_evaluation_script__:10:45
    at ExecutionContext._evaluateInternal (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.sendMessage (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/Client.js:686:28)

Node.js v19.7.0

How can I rectify it?

**Comment by NicoNicoNico123** [comment]
I face that error too, no hope

**Comment by adamshand** [comment]
Same.

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
