### ISSUE TITLE
Docker doesn't start without SerpAPI

### ISSUE THREAD

**Issue by cutzenfriend** [askrella/whatsapp-chatgpt#190]
```
whatsapp-chatgpt-whatsapp-chatgpt-1  |
whatsapp-chatgpt-whatsapp-chatgpt-1  | > whatsapp-chatgpt@1.0.0 start
whatsapp-chatgpt-whatsapp-chatgpt-1  | > npx vite-node src/index.ts
whatsapp-chatgpt-whatsapp-chatgpt-1  |
whatsapp-chatgpt-whatsapp-chatgpt-1  | (node:31) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
whatsapp-chatgpt-whatsapp-chatgpt-1  |
whatsapp-chatgpt-whatsapp-chatgpt-1  | Please migrate your code to use AWS SDK for JavaScript (v3).
whatsapp-chatgpt-whatsapp-chatgpt-1  | For more information, check the migration guide at https://a.co/7PzMCcy
whatsapp-chatgpt-whatsapp-chatgpt-1  | (Use `node --trace-warnings ...` to show where the warning was created)
whatsapp-chatgpt-whatsapp-chatgpt-1  | [WARN] Importing from 'langchain/llms' is deprecated. Import from eg. 'langchain/llms/openai' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
whatsapp-chatgpt-whatsapp-chatgpt-1  | [WARN] Importing from 'langchain' is deprecated. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
whatsapp-chatgpt-whatsapp-chatgpt-1  | file:///app/node_modules/langchain/dist/tools/serpapi.js:45
whatsapp-chatgpt-whatsapp-chatgpt-1  |             throw new Error("SerpAPI API key not set. You can set it as SERPAPI_API_KEY in your .env file, or pass it to SerpAPI.");
whatsapp-chatgpt-whatsapp-chatgpt-1  |                   ^
whatsapp-chatgpt-whatsapp-chatgpt-1  |
whatsapp-chatgpt-whatsapp-chatgpt-1  | Error: SerpAPI API key not set. You can set it as SERPAPI_API_KEY in your .env file, or pass it to SerpAPI.
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at new SerpAPI (file:///app/node_modules/langchain/dist/tools/serpapi.js:45:19)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at new BrowserAgentProvider (/app/src/providers/browser-agent.ts:9:3)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at /app/src/handlers/langchain.ts:5:22
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.directRequest (file:///app/node_modules/vite-node/dist/client.mjs:331:5)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.cachedRequest (file:///app/node_modules/vite-node/dist/client.mjs:171:14)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.dependencyRequest (file:///app/node_modules/vite-node/dist/client.mjs:220:14)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at /app/src/handlers/message.ts:11:31
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.directRequest (file:///app/node_modules/vite-node/dist/client.mjs:331:5)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.cachedRequest (file:///app/node_modules/vite-node/dist/client.mjs:171:14)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.dependencyRequest (file:///app/node_modules/vite-node/dist/client.mjs:220:14)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at /app/src/index.ts:9:31
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.directRequest (file:///app/node_modules/vite-node/dist/client.mjs:331:5)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.cachedRequest (file:///app/node_modules/vite-node/dist/client.mjs:171:14)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at ViteNodeRunner.executeFile (file:///app/node_modules/vite-node/dist/client.mjs:150:12)
whatsapp-chatgpt-whatsapp-chatgpt-1  |     at CAC.run (file:///app/node_modules/vite-node/dist/cli.mjs:70:5)
whatsapp-chatgpt-whatsapp-chatgpt-1  |
whatsapp-chatgpt-whatsapp-chatgpt-1  | Node.js v19.9.0
whatsapp-chatgpt-whatsapp-chatgpt-1 exited with code 1
```

**Comment by shivindera** [comment]
Same issue

**Comment by jm-rizkallah** [comment]
Can you show your docker-compose so we can help ?

**Comment by cutzenfriend** [comment]
Of course: That's how my compose looks:

```
version: "3"
services:
    whatsapp-chatgpt:
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "APIKEY"
            #PREFIX_ENABLED: ""
            GROUPCHATS_ENABLED: true
            #OPENAI_MODEL: "gpt-4"
            MAX_MODEL_TOKENS: 200
        volumes:
            - session-data:/app/session
volumes:
    session-data:
```

**Comment by envieme** [comment]
You have the version with langchain incorporated for !lang command functionality. Just add             SERPAPI_API_KEY: "xxxxxxxxx" and it will work.

**Comment by joeyxd** [comment]
same issue already tried adding add SERPAPI_API_KEY: "xxxxxxxxx" to Compose
