### ISSUE TITLE
TTS Error

### ISSUE THREAD

**Issue by jm-rizkallah** [askrella/whatsapp-chatgpt#192]
Is anyone receiving this error while TTS is enabled

`◇  [SpeechAPI] Audio generated!
/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^
Error: Evaluation failed: u
    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:686:28)
Node.js v19.9.0
`

**Comment by envieme** [comment]
Yes, I get same error. Unable to figure out why.

**Comment by crypticatul** [comment]
Same here
