### ISSUE TITLE
LangChain [SerpAPI] parse error

### ISSUE THREAD

**Issue by cristigoia** [askrella/whatsapp-chatgpt#201]
For some search queries, I get the following parse error: `Unable to parse JSON response from chat agent.`. First thought it was because of no results, or some special character searches. but not sure anymore (chat example below).

Full error log: 

```
    at ChatAgent.extractToolAndInput (../whatsapp-chatgpt/node_modules/langchain/dist/agents/chat/index.js:83:19)
    at ChatAgent._plan (../whatsapp-chatgpt/node_modules/langchain/dist/agents/agent.js:190:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AgentExecutor._call (../whatsapp-chatgpt/node_modules/langchain/dist/agents/executor.js:78:28)
    at AgentExecutor.call (../whatsapp-chatgpt/node_modules/langchain/dist/chains/base.js:61:28)
    at BrowserAgentProvider.fetch (../whatsapp-chatgpt/src/providers/browser-agent.ts:33:18)
    at Module.handleMessageLangChain (../whatsapp-chatgpt/src/handlers/langchain.ts:12:18)
    at Module.handleIncomingMessage (../whatsapp-chatgpt/src/handlers/message.ts:185:3)
    at Client.<anonymous> (../whatsapp-chatgpt/src/index.ts:80:3)
```

Chat Example:
![pError](https://user-images.githubusercontent.com/7490368/233798949-bc55d8f6-a048-4e71-9339-dda22a51d1a7.jpeg)

**Comment by crypticatul** [comment]
![Screenshot_2023_0423_000120.png](https://user-images.githubusercontent.com/88734298/233801601-6002f72a-c30f-4d73-8f0c-a9d12495bebe.png)

Sane here

**Comment by UN5T48L3** [comment]
I've committed a pr which fixes this issue.
