### ISSUE TITLE
SpeechAPI Error

### ISSUE THREAD

**Issue by ImmortalMan01** [askrella/whatsapp-chatgpt#218]
![image](https://user-images.githubusercontent.com/29338016/236675764-b1da0e09-5421-4318-85e0-a0a22a664863.png)

◇  [SpeechAPI] Generating audio from GPT response "Benim durumum harika, senin durumun nasıl?"...
◇  [SpeechAPI] Audio generated!
C:\Users\Ogulc\Desktop\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: u
    at ExecutionContext._evaluateInternal (C:\Users\Ogulc\Desktop\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (C:\Users\Ogulc\Desktop\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.sendMessage (C:\Users\Ogulc\Desktop\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\src\Client.js:686:28)

Node.js v18.13.0

**Comment by onemind66** [comment]
me too. i am running it in colab. 
maybe you need send the audio as a document
