### ISSUE TITLE
Migrate your code?

### ISSUE THREAD

**Issue by ugurozer84** [askrella/whatsapp-chatgpt#255]
Hello,
I have fixed many things, such as the syntax of '^' in package.json and installation of qrcode-terminal. However, I am still encountering the following error and unable to run it. What do you think might be the problem? 

```
`root@obiziz-digitalocean:~/whatsapp-chatgpt# npm start run

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts run

(node:5632) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[WARN] Importing from 'langchain/llms' is deprecated. Import from eg. 'langchain/llms/openai' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
/root/whatsapp-chatgpt/node_modules/langchain/dist/tools/serpapi.js:47
            throw new Error("SerpAPI API key not set. You can set it as SERPAPI_API_KEY in your .env file, or pass it to SerpAPI.");
                  ^

Error: SerpAPI API key not set. You can set it as SERPAPI_API_KEY in your .env file, or pass it to SerpAPI.
    at new SerpAPI (/root/whatsapp-chatgpt/node_modules/langchain/dist/tools/serpapi.js:45:19)
    at new BrowserAgentProvider (/root/whatsapp-chatgpt/src/providers/browser-agent.ts:8:3)
    at /root/whatsapp-chatgpt/src/handlers/langchain.ts:5:22
    at ViteNodeRunner.directRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:345:5)
    at ViteNodeRunner.cachedRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:190:14)
    at ViteNodeRunner.dependencyRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:235:12)
    at /root/whatsapp-chatgpt/src/handlers/message.ts:7:31
    at ViteNodeRunner.directRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:345:5)
    at ViteNodeRunner.cachedRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:190:14)
    at ViteNodeRunner.dependencyRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:235:12)
    at /root/whatsapp-chatgpt/src/index.ts:5:31
    at ViteNodeRunner.directRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:345:5)
    at ViteNodeRunner.cachedRequest (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:190:14)
    at ViteNodeRunner.executeFile (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:162:12)
    at CAC.run (file:///root/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:70:5)

Node.js v18.13.0
root@obiziz-digitalocean:~/whatsapp-chatgpt# `

Thanks for your help.
```

**Comment by ugurozer84** [comment]
After entering SERPAPI to docker-compose.yml , it solves...

**Comment by navopw** [comment]
What do you mean with "syntax of '^' in package.json and installation of qrcode-terminal".

Can you explain in more detail, so I can adjust our repo? :)

**Comment by ugurozer84** [comment]
https://github.com/askrella/whatsapp-chatgpt/issues/247#issuecomment-1571627529
https://github.com/askrella/whatsapp-chatgpt/issues/252#issue-1747417749
