### ISSUE TITLE
Tengo este error en replit.com

### ISSUE THREAD

**Issue by Danielperfull-00** [askrella/whatsapp-chatgpt#256]
npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:211
      const error = new Error(
                    ^

Error: Cannot find module 'qrcode-terminal' imported from '/@fs//home/runner/GPTWS/src/index.ts'.

- If you rely on tsconfig.json to resolve modules, please install "vite-tsconfig-paths" plugin to handle module resolution.
 - Make sure you don't have relative aliases in your Vitest config. Use absolute paths instead. Read more: https://vitest.dev/guide/common-errors
    at ViteNodeRunner._resolveUrl (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:211:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ViteNodeRunner.resolveUrl (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:228:14)
    at request (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:243:32)
    at /home/runner/GPTWS/src/index.ts:1:31
    at ViteNodeRunner.directRequest (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:345:5)
    at ViteNodeRunner.cachedRequest (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:190:14)
    at ViteNodeRunner.executeFile (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:162:12)
    at CAC.run (file:///home/runner/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:70:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
