### ISSUE TITLE
ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by brickellnetworking** [askrella/whatsapp-chatgpt#261]
After scanning the QR code, the bot works for a few queries and then stops working.  If I terminate, and start again, it goes into a perpetual Starting... but then exits with the following:

Xtuser-MacBook-Pro:whatsapp-chatgpt-master xtuser$ npm start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:18466) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[WARN] Importing from 'langchain/llms' is deprecated. Import from eg. 'langchain/llms/openai' instead. See https://js.langchain.com/docs/getting-started/install#updating-from-0052 for upgrade instructions.
┌   Whatsapp ChatGPT & DALL-E 
│
◇   ────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                   │
│  A Whatsapp bot that uses OpenAI's ChatGPT and DALL-E to generate text and images from a prompt.  │
│                                                                                                   │
├───────────────────────────────────────────────────────────────────────────────────────────────────╯
│
◒  Starting.     
/Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/Connection.ts:300:12)
    at ExecutionContext._evaluateInternal (/Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:254:44)
    at ExecutionContext.evaluateHandle (/Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:193:17)
    at WaitTask.rerun (/Users/xtuser/Documents/whatsapp-chatgpt-master/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/DOMWorld.ts:841:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  originalMessage: ''
}

Node.js v20.1.0

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
