### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by witchfindertr** [askrella/whatsapp-chatgpt#279]
Starting
file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:54867
        const err = new Error(`Failed to load url ${url} (resolved id: ${id})${importer ? ` in ${importer}` : ''}. ${msg}`);
                    ^

Error: Failed to load url C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/run (resolved id: C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/run). Does the file exist?
    at loadAndTransform (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:54867:21)
    at ViteNodeServer._transformRequest (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/server.mjs:360:16)
    at ViteNodeServer._fetchModule (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/server.mjs:331:17)
    at ViteNodeRunner.directRequest (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/client.mjs:233:46)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/client.mjs:184:14)
    at ViteNodeRunner.executeFile (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/client.mjs:152:12)
    at CAC.run (file:///C:/Users/Administrator/Desktop/gonder/whatsapp-chatgpt-master/node_modules/vite-node/dist/cli.mjs:70:5) {
  code: 'ERR_LOAD_URL'

**Comment by connorv001** [comment]
Could you post more details? 
Which version?
Operating system?
When did you encounter this error?
Was it working before?

**Comment by saud121** [comment]
have you solved the issue?
@witchfindertr

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
