### ISSUE TITLE
whatsapp chatgpt new session bug

### ISSUE THREAD

**Issue by emrekaramannnn** [askrella/whatsapp-chatgpt#285]
I've been having problems logging in for the last week. The bot doesn't work. After the client says ready, there is no login screen.

![Bug](https://github.com/askrella/whatsapp-chatgpt/assets/127592314/4207d8f8-06a0-4fc9-b59e-300446bccd39)

**Comment by dermyhzo** [comment]
same issues : 

```
│
◇  Authenticated!
│
◑  Logging in.     
/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/src/Client.js:278:9)

Node.js v18.13.0
root@wa-gpt-debian:~/whatsapp-chatgpt-2# 
```

**Comment by dermyhzo** [comment]
problem fixed

`npm i whatsapp-web.js`

**Comment by emrekaramannnn** [comment]
> npm i whatsapp-web.js

Hi dermyhzo,

npm i whatsapp-web.js

I ran this command but it didn't fix it. Session process does not start
![123](https://github.com/askrella/whatsapp-chatgpt/assets/127592314/ac6bac71-1405-4db4-9ce8-487de83d5c06)

If you have the possibility to send me all working files, that would be great.

**Comment by emrekaramannnn** [comment]
I have reinstalled the script and I am trying to solve the problems step by step. The first error is below.

PS C:\8> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:5472) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
C:\8\node_modules\langchain\dist\callbacks\handlers\console.js:25
const { color } = __vite_ssr_import_0__.default;
        ^

TypeError: Cannot destructure property 'color' of '__vite_ssr_import_0__.default' as it is undefined.
    at C:\8\node_modules\langchain\dist\callbacks\handlers\console.js:25:9
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\callbacks\manager.js:3:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\llms\base.js:4:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\llms\index.js:1:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)

Node.js v18.16.0
PS C:\8>

**Comment by emrekaramannnn** [comment]
Can anyone solve this problem? The bot is not working.

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
