### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')

### ISSUE THREAD

**Issue by brickellnetworking** [askrella/whatsapp-chatgpt#287]
Getting the following now, any ideas?

`◇  Authenticated!
│
◑  Logging in..    
/Users/nas/Documents/GitHub/whatsapp-chatgpt3/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/Users/nas/Documents/GitHub/whatsapp-chatgpt3/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/Users/nas/Documents/GitHub/whatsapp-chatgpt3/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/Users/nas/Documents/GitHub/whatsapp-chatgpt3/node_modules/whatsapp-web.js/src/Client.js:278:9)

Node.js v18.16.1
nas@nass-mac-mini whatsapp-chatgpt3 % `

**Comment by dermyhzo** [comment]
same issues  :

```
│
◇  Authenticated!
│
◑  Logging in.     
/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/src/Client.js:278:9)

Node.js v18.13.0
root@wa-gpt-debian:~/whatsapp-chatgpt-2# 
```

**Comment by dermyhzo** [comment]
try run 
`npm i whatsapp-web.js`

**Comment by emrekaramannnn** [comment]
> try run `npm i whatsapp-web.js`

You have written this command in all the threads, but this is not the solution.

**Comment by brickellnetworking** [comment]
This did work for me

**Comment by NavinSiHive** [comment]
I am also getting this issue. Kindly can anyone help guiding the optimal solution, to get rid of this critical issue?

**Comment by NavinSiHive** [comment]
Whenever I am deleting message (for everyone), then this engine exits. Whereas, when I delete message (for me), then this engine does not exit, and continues to respond normal.

Can someone help to get rid of this issue ?
