### ISSUE TITLE
Error: Parse failure: Octal literal in strict mode (3:13)

### ISSUE THREAD

**Issue by dermyhzo** [askrella/whatsapp-chatgpt#288]
root@wagpt:/srv/users/chat/apps/chat/public/whatsapp-chatgpt# npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55343
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: /srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55343:15)
    at ssrTransform (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55318:12)
    at Object.ssrTransform (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:64992:20)
    at loadAndTransform (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:54989:24)
    at ViteNodeServer._transformRequest (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite-node/dist/server.mjs:369:16)
    at ViteNodeServer._fetchModule (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite-node/dist/server.mjs:336:17)
    at ViteNodeRunner.directRequest (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:235:46)
    at ViteNodeRunner.cachedRequest (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///srv/users/chat/apps/chat/public/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:221:12)
    at /srv/users/chat/apps/chat/public/whatsapp-chatgpt/src/index.ts:1:31

Node.js v18.0.0

**Comment by dermyhzo** [comment]
Trying to update NPM

```
root@wagpt:/srv/users/chat/apps/chat/public/whatsapp-chatgpt# npm update

npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported

added 2 packages, removed 51 packages, changed 3 packages, and audited 223 packages in 2m

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

but still error when starting run

**Comment by dermyhzo** [comment]
Trying to re-install in debian, same error :

`root@wa-gpt-debian:~/whatsapp-chatgpt# npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported

added 219 packages, and audited 221 packages in 2m

33 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
root@wa-gpt-debian:~/whatsapp-chatgpt# npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///root/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55343
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: /root/whatsapp-chatgpt/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///root/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55343:15)
    at ssrTransform (file:///root/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:55318:12)
    at Object.ssrTransform (file:///root/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:64992:20)
    at loadAndTransform (file:///root/whatsapp-chatgpt/node_modules/vite/dist/node/chunks/dep-df561101.js:54989:24)
    at ViteNodeServer._transformRequest (file:///root/whatsapp-chatgpt/node_modules/vite-node/dist/server.mjs:369:16)
    at ViteNodeServer._fetchModule (file:///root/whatsapp-chatgpt/node_modules/vite-node/dist/server.mjs:336:17)
    at ViteNodeRunner.directRequest (file:///root/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:235:46)
    at ViteNodeRunner.cachedRequest (file:///root/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///root/whatsapp-chatgpt/node_modules/vite-node/dist/client.mjs:221:12)
    at /root/whatsapp-chatgpt/src/index.ts:1:31

Node.js v18.13.0
root@wa-gpt-debian:~/whatsapp-chatgpt# 
`

**Comment by dermyhzo** [comment]
Problem above was FIXED, 
new problem after whatsapp authenticated :

```
│
◇  Authenticated!
│
◑  Logging in.     
/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/src/Client.js:278:9)

Node.js v18.13.0
root@wa-gpt-debian:~/whatsapp-chatgpt-2# 
```

**Comment by dermyhzo** [comment]
problem above fixed after 

`npm i whatsapp-web.js`

**Comment by thenetguy** [comment]
> problem above fixed after npm i whatsapp-web.js

are you able to get a reply , i tried your suggestion but get no reply and no error.
whatsapp-chatgpt  | ◇  Authenticated!
│
whatsapp-chatgpt  | ◇  Session started!
│
whatsapp-chatgpt  | ◇  Loaded!
whatsapp-chatgpt  | │
whatsapp-chatgpt  | └  Whatsapp ChatGPT & DALLE is ready to use.
whatsapp-chatgpt  | 
whatsapp-chatgpt  | [AI-Config] Initialized AI config
whatsapp-chatgpt  | ◇  [GPT] Received prompt from 1555555555@c.us: Hi
whatsapp-chatgpt  | ◇  [GPT] New conversation for 15555555555@c.us (ID: ******************************)

**Comment by sk77github** [comment]
> Problem above was FIXED, new problem after whatsapp authenticated :
> 
> ```
> │
> ◇  Authenticated!
> │
> ◑  Logging in.     
> /root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
>             throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
>                   ^
> 
> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
>     at __puppeteer_evaluation_script__:9:66
>     at ExecutionContext._evaluateInternal (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at ExecutionContext.evaluate (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
>     at Client.initialize (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/src/Client.js:278:9)
> 
> Node.js v18.13.0
> root@wa-gpt-debian:~/whatsapp-chatgpt-2# 
> ```

how did you fix the Error: Parse failure: Octal literal in strict mode (3:13) problem ?

**Comment by sk77github** [comment]
> > Problem above was FIXED, new problem after whatsapp authenticated :
> > ```
> > │
> > ◇  Authenticated!
> > │
> > ◑  Logging in.     
> > /root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
> >             throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
> >                   ^
> > 
> > Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
> >     at __puppeteer_evaluation_script__:9:66
> >     at ExecutionContext._evaluateInternal (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
> >     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at ExecutionContext.evaluate (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
> >     at Client.initialize (/root/whatsapp-chatgpt-2/node_modules/whatsapp-web.js/src/Client.js:278:9)
> > 
> > Node.js v18.13.0
> > root@wa-gpt-debian:~/whatsapp-chatgpt-2# 
> > ```
> 
> how did you fix the Error: Parse failure: Octal literal in strict mode (3:13) problem ?

i fixed the problem, when i find this issue : https://github.com/askrella/whatsapp-chatgpt/issues/254
just Specify the version when installing vite-node from @leoliew 
so, i edited the package.json 
and works

**Comment by emrekaramannnn** [comment]
> problem above fixed after
> 
> `npm i whatsapp-web.js`

PS C:\8> npm update
npm WARN deprecated puppeteer@13.7.0: < 19.4.0 is no longer supported

added 9 packages, removed 7 packages, changed 31 packages, and audited 223 packages in 2m

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\8> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:8080) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
C:\8\node_modules\langchain\dist\callbacks\handlers\console.js:25
const { color } = __vite_ssr_import_0__.default;
        ^

TypeError: Cannot destructure property 'color' of '__vite_ssr_import_0__.default' as it is undefined.
    at C:\8\node_modules\langchain\dist\callbacks\handlers\console.js:25:9
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\callbacks\manager.js:3:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\llms\base.js:4:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\8\node_modules\langchain\dist\llms\index.js:1:31
    at ViteNodeRunner.directRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/8/node_modules/vite-node/dist/client.mjs:221:12)

Node.js v18.16.0
PS C:\8>

**Comment by Aj-Butt** [comment]
PS C:\Users\Aj\Pictures\whatsapp-gpt-mobilink> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts  

(node:2076) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\callbacks\handlers\console.js:25
const { color } = __vite_ssr_import_0__.default;
        ^

TypeError: Cannot destructure property 'color' of '__vite_ssr_import_0__.default' as it is undefined.
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\callbacks\handlers\console.js:25:9
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\callbacks\manager.js:3:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\llms\base.js:4:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\llms\index.js:1:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
221:12)

**Comment by Aj-Butt** [comment]
PS C:\Users\Aj\Pictures\whatsapp-gpt-warid> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite/dist/node/chunks/dep-df561101.js:55343        
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite/dist/node/chunks/dep-df561101.js:55343:15)
    at ssrTransform (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite/dist/node/chunks/dep-df561101.js:55318:12)
    at Object.ssrTransform (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite/dist/node/chunks/dep-df561101.js:64992:20)
    at loadAndTransform (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite/dist/node/chunks/dep-df561101.js:54989:24)
    at ViteNodeServer._transformRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite-node/dist/server.mjs:369:16)
    at ViteNodeServer._fetchModule (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite-node/dist/    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite-node/dist/client.mjs:235:46)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-warid/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-warid\src\index.ts:1:31

**Comment by choudhryfrompak** [comment]
is this issue fixed ...
the latest one

**Comment by emrekaramannnn** [comment]
Can anyone solve this problem? The bot is not working.

**Comment by emrekaramannnn** [comment]
![1](https://github.com/askrella/whatsapp-chatgpt/assets/127592314/65fa4575-72da-4142-8c9b-1d0bacfa1ded)

session cannot be started...

**Comment by jerryrat** [comment]
`npm i whatsapp-web.js@1.22.2-alpha.0`  working

**Comment by emrekaramannnn** [comment]
> `npm i whatsapp-web.js@1.22.2-alpha.0` working

![1](https://github.com/askrella/whatsapp-chatgpt/assets/127592314/13417f28-2a6c-419b-b2f3-09f90291bd3a)

Unfortunately it didn't work.

**Comment by RadientBrain** [comment]
Just use `npm i -U qrcode-terminal`

And it will work, solves for me!

**Comment by Isaakkamau** [comment]
The issue is that you're using octal escape sequences in the black and white variables. Please navigate to this directory:
`qrcode-terminal/lib/main.js`
Locate this code:
```
black = "\033[40m  \033[0m",
white = "\033[47m  \033[0m",
```
and change it to:
```
black = "\u001B[40m  \u001B[0m",
white = "\u001B[47m  \u001B[0m",
```
We have replaced "\033" with "\u001B", which is the Unicode escape sequence for the Escape character (ASCII code 27), followed by [40m and [0m, which are used to set the background color to black and reset the color, respectively.

Hope this helps someone. Thanks

**Comment by navopw** [comment]
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!
