### ISSUE TITLE
How can i run this on a VPS ?

### ISSUE THREAD

**Issue by siulynot** [askrella/whatsapp-chatgpt#30]
When i try to run this on a VPS i get this error: 

```whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/siu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/siu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/home/siu/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:524:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v19.6.1
```
Seems like a problem with puppeteer not being able to open a browser instance... 

Could you help me run this on a VPS with no UI?

**Comment by siulynot** [comment]
Installed chromium, but now i get this error:

```npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:2832645) UnhandledPromiseRejectionWarning: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:724:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
    at link (internal/modules/esm/module_job.js:49:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2832645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:2832645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by gihnih** [comment]
Try use node v18-LTS.

**Comment by connorv001** [comment]
It works beautifully with this Dockerfile:
```
FROM node:lts-bullseye

WORKDIR /tmp/app/

COPY . .

RUN npm install
RUN npm install vite-node
RUN apt-get update
RUN apt-get install chromium -y
CMD ["npm","run","start"]
```

**Comment by EzxD** [comment]
Chromium is no longer used in this project.
Please update the code on your machine. And rerun your the installation process.

**Comment by navopw** [comment]
> @siulynot Chromium is no longer used in this project. Please update the code on your machine. And rerun the installation process.

It is actually used by the whatsapp web client I think.

**Comment by badermq76** [comment]
Running & tested below steps on Debian(11) container.

Step1- If on root user : create a new user and add it to sudo group then switch to the new user(if not skip to the next step):
adduser xxxx
usermod -aG sudo xxxx
su xxxx


Step2- Clone this repository:
sudo apt update
sudo apt install git -y
sudo git clone https://github.com/navopw/whatsapp-chatgpt.git
(this step will create a new folder whatsapp-chatgpt )

Step3- Install the required packages by running npm install:
sudo apt install npm -y
sudo npm install -g n
sudo n lts  //to update npm to latest
sudo apt-get install chromium -y
cd whatsapp-chatgpt  //if you can not cd to folder using new added user in step1, exit to go back to root then cd to folder then su to the new added user.
sudo npm install

Step4-Put your OpenAI API Key into the .env File (OPENAI_API_KEY)
sudo nano .env  //to create and save the .env file with your details as below

OPENAI_API_KEY=xx-user chat gpt key--xx
PREFIX_ENABLED=true


Step5- Run the bot using npm run start:
cd whatsapp-chatgpt
sudo npm run start

    Scan the QR Code with Whatsapp (Link a device)
    Now you're ready to go, people can send you messages and the bot will respond to them.

**Comment by kingofkillers91** [comment]
HI there, what VPS are u using?

**Comment by navopw** [comment]
@badermq76 Nice instructions but please note that the repo URL has changed now :)

https://github.com/askrella/whatsapp-chatgpt

**Comment by siulynot** [comment]
This is the VPS i run: `Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-121-generic x86_64)`

**Comment by siulynot** [comment]
I should clarify this is a vps i have had running for some time it may not have the most up to date packages. I was able to install and use successfully the bot on another server with more recent packages. Might be ok to close this ticket sine the issue might be my own installation.

**Comment by navopw** [comment]
Okay nice, hope you have fun with this bot :)

Will close the ticket for now.
