### ISSUE TITLE
Color error in the commit `cbd544f13`

### ISSUE THREAD

**Issue by RadientBrain** [askrella/whatsapp-chatgpt#302]
Can't run the app due to it giving the following error after [this commit](https://github.com/askrella/whatsapp-chatgpt/commit/cbd544f13233a04cc63184ee0b12e53b5d92ae91):
```
npm start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:1182) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
/home/runner/WhatsappGPT/whatsapp-chatgpt/node_modules/langchain/dist/callbacks/handlers/console.js:25
const { color } = __vite_ssr_import_0__.default;
        ^

TypeError: Cannot destructure property 'color' of '__vite_ssr_import_0__.default' as it is undefined.
    at /home/runner/WhatsappGPT/whatsapp-chatgpt/node_modules/langchain/dist/callbacks/handlers/console.js:23:9
    at ViteNodeRunner.directRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:221:12)
    at /home/runner/WhatsappGPT/whatsapp-chatgpt/node_modules/langchain/dist/callbacks/manager.js:3:31
    at ViteNodeRunner.directRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:221:12)
    at /home/runner/WhatsappGPT/whatsapp-chatgpt/node_modules/langchain/dist/schema/runnable/base.js:2:31
    at ViteNodeRunner.directRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:221:12)
    at /home/runner/WhatsappGPT/whatsapp-chatgpt/node_modules/langchain/dist/schema/runnable/index.js:1:31
    at ViteNodeRunner.directRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///home/runner/WhatsappGPT/node_modules/vite-node/dist/client.mjs:221:12)

Node.js v18.12.1
```

@navopw  I think you can look into this?

**Comment by RadientBrain** [comment]
I think this was because of the caching, I restarted and cleared cache and its working fine!
