### ISSUE TITLE
New error 

### ISSUE THREAD

**Issue by witchfindertr** [askrella/whatsapp-chatgpt#336]
Whatsapp ChatGPT & DALL-E
|-------------------------------------------------------------------------------------------------|
| A Whatsapp bot that uses OpenAI's ChatGPT and DALL-E to generate text and images from a prompt. |
|-------------------------------------------------------------------------------------------------|

C:\Users\Administrator\Desktop\a\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (C:\Users\Administrator\Desktop\a\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\Users\Administrator\Desktop\a\whatsapp-chatgpt-master\node_modules\whatsapp-web.js\src\Client.js:729:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.0

**Comment by connorv001** [comment]
Which version are you using?

**Comment by Cryptoverso** [comment]
Alguma solução? estou tento o mesmo problema!! :( 
└── whatsapp-web.js@1.22.1

/Users/guilhermemelo/Codes/CoinNodes/chatbot/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/Users/guilhermemelo/Codes/CoinNodes/chatbot/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /Users/guilhermemelo/Codes/CoinNodes/chatbot/node_modules/whatsapp-web.js/src/Client.js:729:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.12.0

**Comment by hkvincent** [comment]
need to change the "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_7" to "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_11" in package.json

**Comment by rikuddo91** [comment]
> This worked for me:
> 
> npm update whatsapp-web.js

Still giving me the error after scanning the QR Code,

`E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:5:95
    at ExecutionContext._evaluateInternal (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.initialize (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\src\Client.js:327:9)

Node.js v18.18.0`

**Comment by connorv001** [comment]
> > > This worked for me:
> > > npm update whatsapp-web.js
> > 
> > 
> > Still giving me the error after scanning the QR Code,
> > `E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221 throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails)); ^
> > Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') at **puppeteer_evaluation_script**:5:95 at ExecutionContext._evaluateInternal (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ExecutionContext.evaluate (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12) at Client.initialize (E:\Temp\whatsapp-chatgpt\node_modules\whatsapp-web.js\src\Client.js:327:9)
> > Node.js v18.18.0`
> 
> Yeah still not working for me either after the update..

Did you update?

**Comment by rikuddo91** [comment]
> Did you update?

Yes, I did.

**Comment by connorv001** [comment]
> > Did you update?
> 
> Yes, I did.

what's the verison of whatsapp-webjs

**Comment by rikuddo91** [comment]
> > > Did you update?
> > 
> > 
> > Yes, I did.
> 
> what's the verison of whatsapp-webjs

So I ran `npm update whatsapp-web.js`

version": "1.22.1"

**Comment by connorv001** [comment]
> > > > Did you update?
> > > 
> > > 
> > > Yes, I did.
> > 
> > 
> > what's the verison of whatsapp-webjs
> 
> So I ran `npm update whatsapp-web.js`
> 
> and it updated to version": "1.22.1"

Try updating puppeteer aslo

**Comment by connorv001** [comment]
> > > > Did you update?
> > > 
> > > 
> > > Yes, I did.
> > 
> > 
> > what's the verison of whatsapp-webjs
> 
> So I ran `npm update whatsapp-web.js`
> 
> and it updated to version": "1.22.1"

Are you running linux/dockeR?

**Comment by rikuddo91** [comment]
> > > > > Did you update?
> > > > 
> > > > 
> > > > Yes, I did.
> > > 
> > > 
> > > what's the verison of whatsapp-webjs
> > 
> > 
> > So I ran `npm update whatsapp-web.js`
> > and it updated to version": "1.22.1"
> 
> Are you running linux/dockeR?

No, simple Windows 10.

**Comment by connorv001** [comment]
> > > > > > Did you update?
> > > > > 
> > > > > 
> > > > > Yes, I did.
> > > > 
> > > > 
> > > > what's the verison of whatsapp-webjs
> > > 
> > > 
> > > So I ran `npm update whatsapp-web.js`
> > > and it updated to version": "1.22.1"
> > 
> > 
> > Are you running linux/dockeR?
> 
> No, simple Windows 10.

Tried updating pupetter? waht's ypour node verison?

**Comment by hkvincent** [comment]
> > need to change the "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_7" to "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_11" in package.json
> 
> This didn't help :( <img alt="SCR-20240404-pudy" width="1440" src="https://private-user-images.githubusercontent.com/127094608/319642978-4add6dae-9a0b-412c-9d06-9ccfcee0d5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzAzNTEsIm5iZiI6MTcxMjM3MDA1MSwicGF0aCI6Ii8xMjcwOTQ2MDgvMzE5NjQyOTc4LTRhZGQ2ZGFlLTlhMGItNDEyYy05ZDA2LTljY2ZjZWUwZDVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwMjIwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjM3MGY3NjMzMDUyZDE0ZDMyODMyZTRmNGJhZDMzY2VlOTc3Y2RmZDEyZDRkYmQ1ODc1ODlkNzkwNGVlYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._M28Yxbd0Tcn9yZgrIlj1XYVgTOyAgRKb3rfPae1Rfc">

Did you run 'npm install' after changing to the new version? The issue is definitely related to the version of web.js.

**Comment by GreenerX** [comment]
> > > need to change the "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_7" to "whatsapp-web.js": "https://github.com/Julzk/whatsapp-web.js/tarball/jkr_hotfix_11" in package.json
> > 
> > 
> > This didn't help :( <img alt="SCR-20240404-pudy" width="1440" src="https://private-user-images.githubusercontent.com/127094608/319642978-4add6dae-9a0b-412c-9d06-9ccfcee0d5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzAzNTEsIm5iZiI6MTcxMjM3MDA1MSwicGF0aCI6Ii8xMjcwOTQ2MDgvMzE5NjQyOTc4LTRhZGQ2ZGFlLTlhMGItNDEyYy05ZDA2LTljY2ZjZWUwZDVlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwMjIwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjM3MGY3NjMzMDUyZDE0ZDMyODMyZTRmNGJhZDMzY2VlOTc3Y2RmZDEyZDRkYmQ1ODc1ODlkNzkwNGVlYzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._M28Yxbd0Tcn9yZgrIlj1XYVgTOyAgRKb3rfPae1Rfc">
> 
> Did you run 'npm install' after changing to the new version? The issue is definitely related to the version of web.js.

My JSON looks like this after the npm update and npm install:
<img width="912" alt="SCR-20240406-iwyt" src="https://github.com/askrella/whatsapp-chatgpt/assets/127094608/57ade46f-559e-488e-ba65-688c16c153f9">

**Comment by GreenerX** [comment]
Now its just stuck on this:
<img width="873" alt="SCR-20240406-iyad" src="https://github.com/askrella/whatsapp-chatgpt/assets/127094608/15efbb5e-9440-4fd2-8eef-680f4a2b28c3">

**Comment by ClaytonCassi** [comment]
doing this step: 
```
const client = new Client({
		puppeteer: {
			args: ["--no-sandbox"]
		},
		webVersionCache: {
			type: 'remote',
			remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
		},
		authStrategy: new LocalAuth({
			dataPath: constants.sessionPath
		})
	});
```
I solve this error ->   const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
TypeError: Cannot read properties of null (reading '1')

but its raise a new puppetter error - >  throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));      
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')
this error persist even when u update puppeteer and whatsappweb.js to lastest version.

Has anyone managed to get the application to work?

**Comment by zzzeven** [comment]
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

**Comment by brumatx** [comment]
> npm install github:pedroslopez/whatsapp-web.js#webpack-exodus

The best aswer... works for me!!

**Comment by Isaakkamau** [comment]
I will just drop my debugging steps here.

1. First of all I deleted all this folders, if they are available in your project:  "node_modules", "session", ".wwebjs_cache"
2.  Replace you package.json with this one:
`
{
	"name": "whatsapp-chatgpt",
	"version": "1.0.0",
	"description": "Whatsapp bot that uses OpenAI's GPT & DALLE to respond to user inputs",
	"main": "src/index.ts",
	"author": "Askrella Software Agency UG (haftungsbeschränkt)",
	"scripts": {
		"start": "npx vite-node src/index.ts",
		"prettier": "prettier --write ./src"
	},
	"license": "MIT",
	"dependencies": {
		"aws-sdk": "^2.1467.0",
		"chatgpt": "^5.2.5",
		"dotenv": "^16.3.1",
		"fetch-blob": "^4.0.0",
		"ffmpeg": "^0.0.4",
		"langchain": "^0.0.156",
		"openai": "^3.3.0",
		"picocolors": "^1.0.0",
		"qrcode": "^1.5.3",
		"whatsapp-web.js": "github:pedroslopez/whatsapp-web.js#webpack-exodus"
	},
	"engines": {
		"node": ">=18.0.0"
	},
	"devDependencies": {
		"@types/qrcode": "^1.5.2",
		"prettier": "^3.0.3"
	}
}

`

3. Re-run: `npm install`
4. finally: `npm run start`

**Comment by Cryptoverso** [comment]
github:pedroslopez/whatsapp-web.js#webpack-exodus está fora, 

como fazer agora?
