### ISSUE TITLE
Error at DALL-E]

### ISSUE THREAD

**Issue by brumatx** [askrella/whatsapp-chatgpt#339]
◇  [DALL-E] Received prompt from 351965417125@c.us: botafogo
An error occured TypeError: Cannot read properties of undefined (reading 'createImage')
    at Module.handleMessageDALLE (/home/brmx/bot/whatsapp-chatgpt/src/handlers/dalle.ts:28:33)
    at Module.handleIncomingMessage (/home/brmx/bot/whatsapp-chatgpt/src/handlers/message.ts:153:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Client.<anonymous> (/home/brmx/bot/whatsapp-chatgpt/src/index.ts:101:3)

Anyone know how to fiz it?

**Comment by DreamCloudProject** [comment]
Same problem!
