### ISSUE TITLE
Doesn't run on Raspberry Pi 4

### ISSUE THREAD

**Issue by byt3magic** [askrella/whatsapp-chatgpt#73]
pi@pi:~/whatsapp-chatgpt $ npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

┌   Whatsapp ChatGPT & DALL-E 
│
◇   ────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                   │
│  A Whatsapp bot that uses OpenAI's ChatGPT and DALL-E to generate text and images from a prompt.  │
│                                                                                                   │
├───────────────────────────────────────────────────────────────────────────────────────────────────╯
│
○  Starting
/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: Syntax error: ")" unexpected

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/home/pi/whatsapp-chatgpt/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.14.1

**Comment by connorv001** [comment]
I can guide you, please join on our discord and ping me 
"@Shub"

**Comment by byt3magic** [comment]
I managed to install it on a Windows server.
